# Generated by Django 4.2.4 on 2023-12-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='dt',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
